<option value="آمریکا">آمریکا</option>
<option value="چین">چین</option>
<option value="ژاپن">ژاپن</option>
<option value="آلمان">آلمان</option>
<option value="فرانسه">فرانسه</option>
<option value="بریتانیا">بریتانیا</option>
<option value="سوئیس">سوئیس</option>
<option value="کانادا">کانادا</option>
<option value="هلند">هلند</option>
<option value="بلژیک">بلژیک</option>
<option value="ایتالیا">ایتالیا</option>
<option value="اسپانیا">اسپانیا</option>
<option value="کره جنوبی">کره جنوبی</option>
<option value="سوئد">سوئد</option>
<option value="استرالیا">استرالیا</option>
<option value="بلاروس">بلاروس</option>
<option value="برزیل">برزیل</option>
<option value="تایوان">تایوان</option>
<option value="ترکیه">ترکیه</option>
<option value="ایرلند">ایرلند</option>
<option value="ایسلند">ایسلند</option>
<option value="نروژ">نروژ</option>
<option value="دانمارک">دانمارک</option>
<option value="فنلاند">فنلاند</option>
<option value="سنگاپور">سنگاپور</option>
<option value="ایران">ایران</option>
<option value="پاکستان">پاکستان</option>
<option value="مالزی">مالزی</option>
<option value="هند">هند</option>
<option value="روسیه">روسیه</option>
<option value="مکزیک">مکزیک</option>
<option value="آرژانتین">آرژانتین</option>
<option value="شیلی">شیلی</option>
<option value="کلمبیا">کلمبیا</option>
<option value="ونزوئلا">ونزوئلا</option>
<option value="مصر">مصر</option>
<option value="سعودی">سعودی</option>
<option value="مراکش">مراکش</option>
<option value="جنوب آفریقا">جنوب آفریقا</option>
<option value="نیجریه">نیجریه</option>
<option value="کنیا">کنیا</option>
<option value="عراق">عراق</option>
<option value="کویت">کویت</option>
<option value="قطر">قطر</option>
<option value="امارات متحده عربی">امارات متحده عربی</option>
<option value="عمان">عمان</option>
<option value="یمن">یمن</option>
<option value="کوبا">کوبا</option>
<option value="ونزوئلا">ونزوئلا</option>
<option value="نیکاراگوئه">نیکاراگوئه</option>
<option value="گواتمالا">گواتمالا</option>
<option value="هندوراس">هندوراس</option>
<option value="کوستاریکا">کوستاریکا</option>
<option value="پاناما">پاناما</option>
<option value="بولیوی">بولیوی</option>
<option value="پرو">پرو</option>
<option value="چیلی">چیلی</option>
<option value="اکوادور">اکوادور</option>
<option value="کوهر">کوهر</option>
<option value="جمهوری دومینیکن">جمهوری دومینیکن</option>
<option value="گویان">گویان</option>
<option value="سورینام">سورینام</option>
<option value="گویان فرانسه">گویان فرانسه</option>
<option value="هائیتی">هائیتی</option>
<option value="جامائیکا">جامائیکا</option>
<option value="بهاماس">بهاماس</option>
<option value="ترینیداد و توباگو">ترینیداد و توباگو</option>
<option value="آنتیگوا و باربودا">آنتیگوا و باربودا</option>
<option value="سنت کیتس و نویس">سنت کیتس و نویس</option>
<option value="سنت لوسیا">سنت لوسیا</option>
<option value="باربادوس">باربادوس</option>

